import glob

Import('test_env')
test_env.Program('openmp.cpp')

nvcc_exists = test_env.Detect('nvcc')
if nvcc_exists:

    sources = glob.glob('*.cu')

    for source in sources:
        test_env.Program(source)

